name = "SOQL"
grammar = "soql"
path_suffixes = ["soql"]
line_comments = ["// "]
brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
]
