id = "apex"
name = "Apex"
version = "0.0.3"
schema_version = 1
authors = ["igorcguedes <igorcguedes@proton.me>", "jasonkradams <jason@jadams.pw>"]
description = "Provides Apex syntax highlighting in Zed"
repository = "https://github.com/jasonkradams/zed-apex"

[grammars.apex]
repository = "https://github.com/aheber/tree-sitter-sfapex.git"
commit = "3597575a429766dd7ecce9f5bb97f6fec4419d5d"
path = "apex"

[grammars.soql]
repository = "https://github.com/aheber/tree-sitter-sfapex.git"
commit = "3597575a429766dd7ecce9f5bb97f6fec4419d5d"
path = "soql"

[grammars.sosl]
repository = "https://github.com/aheber/tree-sitter-sfapex.git"
commit = "3597575a429766dd7ecce9f5bb97f6fec4419d5d"
path = "sosl"
